-- شغّل هذا الملف داخل Supabase Studio > SQL Editor

create table if not exists public.tasks (
  id           bigint generated by default as identity primary key,
  title        text not null,
  quadrant     text not null default 'important-urgent'
               check (quadrant in (
                 'important-urgent',
                 'important-not-urgent',
                 'not-important-urgent',
                 'not-important-not-urgent'
               )),
  context      text not null default 'work',
  subtasks     jsonb not null default '[]'::jsonb,
  completed    boolean not null default false,
  archived     boolean not null default false,
  archived_at  timestamptz,
  notes        text default '',
  due_date     date,
  duration     integer not null default 1,
  sort_order   integer not null default 0,
  recurrence   text default null,
  recurrence_days integer[] default null,
  external_source text default null,
  external_id     text default null,
  external_url    text default null,
  external_meta   jsonb default null,
  last_synced_at  timestamptz,
  created_at   timestamptz not null default now(),
  completed_at timestamptz
);

-- ترحيل
alter table public.tasks add column if not exists context text not null default 'work';
alter table public.tasks add column if not exists subtasks jsonb not null default '[]'::jsonb;
alter table public.tasks drop constraint if exists tasks_context_check;
alter table public.tasks add column if not exists sort_order integer not null default 0;
alter table public.tasks add column if not exists recurrence text default null;
alter table public.tasks add column if not exists recurrence_days integer[] default null;
alter table public.tasks add column if not exists external_source text default null;
alter table public.tasks add column if not exists external_id text default null;
alter table public.tasks add column if not exists external_url text default null;
alter table public.tasks add column if not exists external_meta jsonb default null;
alter table public.tasks add column if not exists last_synced_at timestamptz;
alter table public.tasks add column if not exists archived boolean not null default false;
alter table public.tasks add column if not exists archived_at timestamptz;

update public.tasks set context = 'work' where context is null or btrim(context) = '';
update public.tasks set archived = false where archived is null;

create unique index if not exists tasks_external_unique
  on public.tasks (external_source, external_id)
  where external_source is not null and external_id is not null;

create index if not exists tasks_created_at_idx on public.tasks (created_at desc);
create index if not exists tasks_quadrant_sort_idx on public.tasks (quadrant, sort_order);
create index if not exists tasks_context_idx on public.tasks (context);
create index if not exists tasks_archived_idx on public.tasks (archived);

create table if not exists public.integrations (
  id            bigint generated by default as identity primary key,
  provider      text not null unique,
  api_key       text,
  access_token  text,
  settings      jsonb default '{}'::jsonb,
  last_sync_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table public.tasks enable row level security;
alter table public.integrations enable row level security;

drop policy if exists "Allow all access to tasks" on public.tasks;
create policy "Allow all access to tasks"
  on public.tasks for all using (true) with check (true);

drop policy if exists "Allow all access to integrations" on public.integrations;
create policy "Allow all access to integrations"
  on public.integrations for all using (true) with check (true);

do $$
begin
  alter publication supabase_realtime add table public.tasks;
exception when duplicate_object then null;
end $$;
